name: release
on:
  workflow_dispatch: 
  
jobs:
  release-linux:
    name: Run npm on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'
          cache: true
      - run: flutter --version
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter build linux --release
      - run: zip linux_x64 build/linux/x64/release/bundle -r
      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: linux_x64

          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: build/linux/x64/release/bundle/linux_x64.zip