name: release
on:
  workflow_dispatch: 
  
jobs:
  release-linux:
    name: Build Linux app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'
          cache: true
      - run: flutter --version
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y ninja-build libgtk-3-dev
      - run: dart pub global activate flutter_distributor
      - run: flutter_distributor release --name build-linux
      - uses: actions/upload-artifact@v4
        with:
          name: mocker_linux_x64.zip
          path: ./dist/**/*-linux.zip
      - uses: actions/upload-artifact@v4
        with:
          name: mocker_linux_x64.deb
          path: ./dist/**/*.deb
  release-windows:
    name: Build Windows app
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'
          cache: true
      - run: flutter --version
      - run: dart pub global activate flutter_distributor
      - run: flutter_distributor release --name build-windows
      - uses: actions/upload-artifact@v4
        with:
          name: mocker_windows_x64_zip.zip
          path: ./dist/**/*-windows.zip
      - uses: actions/upload-artifact@v4
        with:
          name: mocker_windows_x64_setup.exe
          path: ./dist/**/*-windows-setup.exe
  release-mac:
    name: Build Mac app
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm install -g appdmg 
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.x'
        channel: 'stable'
        cache: true
    - run: flutter --version
    - run: dart pub global activate flutter_distributor
    - run: flutter_distributor release --name build-mac